export const routes = {
  login: "/auth/login",
  registro: "/auth/registro",
  //landing: "/landing",
  miPerfil: "/miPerfil",
  carroCompras: "/carroCompra",
  home: "/",
  nosotros: "/nosotros",
  favoritos: "/favoritos",
  planesRutinas: "/planesRutinas",
  casosExito: "/casosExito",
  tarifas: "/tarifas",
  eventos: "/eventos",
  admin: "/admin",
  adminPublicidad: "/admin/publicidad",
};
