import React from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "../app/styles/globals.css";
import { Bounce, ToastContainer } from "react-toastify";
import Navbar from "./components/navbarFooter/navbar";
import Footer from "./components/navbarFooter/footer";
import { AuthProvider } from "./contextos/contextoAuth";
import VisibleWrapper from "./wrapper/visibleWrapper";
import Script from "next/script";
import { Auth0ProviderWrapper } from "./contextos/contextoAuth0";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
}) as unknown as { variable: string };

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xtreme Gym",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${poppins.variable} antialiased`}>
        {" "}
        <Auth0ProviderWrapper>
          <AuthProvider>
            <VisibleWrapper>
              <Navbar />
            </VisibleWrapper>
            <div>{children}</div>
            <VisibleWrapper>
              <Footer />
            </VisibleWrapper>
            <ToastContainer
              position="top-center"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              transition={Bounce}
              toastClassName="custom-toast"
            />
          </AuthProvider>
        </Auth0ProviderWrapper>
        <script
          src="//code.tidio.co/d5nlufbj8mjvzlknyy2qjjfsgfyn9thb.js"
          async
        ></script>
      </body>
    </html>
  );
}
